# Generated by Django 5.2.6 on 2025-09-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_step_description_step_finished_at_step_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='finished_at',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='finished_at',
            new_name='ended_at',
        ),
    ]
