# Generated by Django 5.2.6 on 2025-09-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_rename_finished_at_step_ended_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='longitude',
            new_name='lng',
        ),
    ]
