# Generated by Django 5.2.6 on 2025-09-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_latitude_step_lat_rename_longitude_step_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
