# Generated by Django 5.2.6 on 2025-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_step_lat_alter_step_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(),
        ),
    ]
