# Generated by Django 5.2.6 on 2025-09-14 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_step_description_alter_trip_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=500)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.step')),
            ],
        ),
    ]
