# Generated by Django 5.2.6 on 2025-09-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_steps', to='trips.photo'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_trips', to='trips.photo'),
        ),
    ]
