# Generated by Django 5.2.6 on 2025-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_step_cover_photo_trip_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Sequence index within a trip starting at 0'),
        ),
    ]
