# Generated by Django 5.2.6 on 2025-09-14 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_step_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='ended_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='End time (editable)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sequence index within a trip starting at 0'),
        ),
        migrations.AlterField(
            model_name='step',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start time (editable)'),
        ),
    ]
